// GAME CONSTANTS
export const GAME_STATES = {
  MENU: 'menu',
  MATATU_SELECT: 'matatu_select',
  PLAYING: 'playing',
  PAUSED: 'paused',
  GAME_OVER: 'game_over',
  POLICE_STATION: 'police_station'
};

export const LANES = {
  LEFT: 0,
  CENTER: 1,
  RIGHT: 2,
  POSITIONS: [25, 50, 75]
};

export const SPEEDS = {
  BASE: 5,
  MIN: 3,
  MAX: 15,
  INCREASE_PER_LEVEL: 0.5
};

export const SPAWN_RATES = {
  OBSTACLE: 1500,
  COLLECTIBLE: 3000,
  TRAFFIC_LIGHT: 30000,
  POLICE: 20000
};

export const POINTS = {
  TIME: 1,
  PASSENGER_CASH: 10,
  PASSENGER_MPESA: 15,
  FUEL: 20,
  FULL_MATATU: 100,
  POLICE_FINE: -100,
  COLLISION: 0
};

export const COLLISION_THRESHOLD = 50;

export const GAME_LOOP_FPS = 60;
export const GAME_LOOP_INTERVAL = 1000 / GAME_LOOP_FPS;

export const TRAFFIC_LIGHT_DURATION = {
  GREEN: 10000,
  YELLOW: 2000,
  RED: 8000
};

export const POLICE_CHASE_SPEED_MULTIPLIER = 1.5;

export const MATATU_CAPACITY = 14;

export default {
  GAME_STATES,
  LANES,
  SPEEDS,
  SPAWN_RATES,
  POINTS,
  COLLISION_THRESHOLD,
  GAME_LOOP_FPS,
  TRAFFIC_LIGHT_DURATION,
  POLICE_CHASE_SPEED_MULTIPLIER,
  MATATU_CAPACITY
};